services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - db
    links:
      - db:database
    networks:
      - app-network
    environment:
      - MYSQL_HOST=database
      - MYSQL_DATABASE=beer
      - MYSQL_ROOT_PASSWORD=root

  db:
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=beer
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local